framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # async: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options: { message_group_id: first_group }

    routing:
      'App\Message\Message': async
